baseURL = "http://example.org/"
languageCode = "en-us"
title = "DirectScale Developers"
theme = "hugo-geekdoc"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  author = "Learning Experience Team"
  description = "A doc site to help our third-party developers to fully extend the DirectScale platform."
  showVisitedLinks = true
  disableInlineCopyToClipBoard = false
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = true
  disableBreadcrumb = false
  disableNextPrev = false
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/foo.css", "css/bar.css"]